"""English translation strings for GEO PDF report."""

STRINGS = {
    # Cover page
    'report_title': 'GEO Analysis Report',
    'report_subtitle': 'Generative Engine Optimization Audit for <b>{brand_name}</b>',
    'label_website': 'Website',
    'label_date': 'Analysis Date',
    'label_score': 'GEO Score',
    'score_of_100': '/100',

    # Score tiers
    'tier_excellent': 'Excellent',
    'tier_good': 'Good',
    'tier_moderate': 'Moderate',
    'tier_below_avg': 'Below Average',
    'tier_needs_attention': 'Needs Attention',

    # Section headers
    'section_executive_summary': 'Executive Summary',
    'section_score_breakdown': 'GEO Score Breakdown',
    'section_platform_readiness': 'AI Platform Readiness',
    'section_crawler_access': 'AI Crawler Access Status',
    'section_findings': 'Key Findings',
    'section_action_plan': 'Prioritized Action Plan',
    'section_methodology': 'Appendix: Methodology',
    'section_glossary': 'Glossary',

    # Table headers
    'col_component': 'Component',
    'col_score': 'Score',
    'col_weight': 'Weight',
    'col_weighted': 'Weighted',
    'col_platform': 'AI Platform',
    'col_status': 'Status',
    'col_crawler': 'Crawler',
    'col_recommendation': 'Recommendation',
    'col_term': 'Term',
    'col_definition': 'Definition',

    # Score components
    'comp_citability': 'AI Citability & Visibility',
    'comp_brand': 'Brand Authority Signals',
    'comp_content': 'Content Quality & E-E-A-T',
    'comp_technical': 'Technical Foundations',
    'comp_schema': 'Structured Data',
    'comp_platform': 'Platform Optimization',
    'comp_overall': 'OVERALL',

    # Chart labels (short)
    'chart_citability': 'Citability',
    'chart_brand': 'Brand',
    'chart_content': 'Content',
    'chart_technical': 'Technical',
    'chart_schema': 'Schema',
    'chart_platform': 'Platform',

    # Descriptions
    'platform_desc': 'These scores reflect how likely your content is to be cited by each AI search platform. A score below 50 indicates significant barriers to citation on that platform.',
    'crawler_desc': 'Blocking AI crawlers prevents AI platforms from citing your content. The table below shows which AI crawlers can currently access your site.',

    # Action plan sub-headers
    'quick_wins_title': 'Quick Wins (This Week)',
    'quick_wins_desc': 'High impact, low effort \u2014 can be implemented immediately.',
    'medium_term_title': 'Medium-Term Improvements (This Month)',
    'medium_term_desc': 'Significant impact, moderate effort \u2014 requires content or technical changes.',
    'strategic_title': 'Strategic Initiatives (This Quarter)',
    'strategic_desc': 'Long-term competitive advantage \u2014 requires ongoing investment.',

    # Header/footer
    'header_text': 'GEO-SEO Analysis Report',
    'footer_generated': 'Generated {date}',
    'footer_page': 'Page {page}',
    'footer_confidential': 'Confidential',

    # Severity labels
    'severity_critical': 'CRITICAL',
    'severity_high': 'HIGH',
    'severity_medium': 'MEDIUM',

    # Fallbacks
    'fallback_exec_summary': 'This report presents the findings of a comprehensive Generative Engine Optimization (GEO) audit conducted on <b>{brand_name}</b> ({url}). The analysis evaluated the website\'s readiness for AI-powered search engines including Google AI Overviews, ChatGPT, Perplexity, Gemini, and Bing Copilot. The overall GEO Readiness Score is <b>{geo_score}/100</b>, placing the site in the <b>{tier}</b> tier.',
    'fallback_no_crawlers': 'Run /geo crawlers to populate this section with AI crawler access data.',
    'fallback_no_findings': 'Run a full /geo audit to populate findings.',

    # Methodology
    'methodology_text': 'This GEO audit was conducted on {date} analyzing {url}. The analysis evaluated the website across six dimensions: AI Citability & Visibility (25%), Brand Authority Signals (20%), Content Quality & E-E-A-T (20%), Technical Foundations (15%), Structured Data (10%), and Platform Optimization (10%).',
    'methodology_platforms': '<b>Platforms assessed:</b> Google AI Overviews, ChatGPT Web Search, Perplexity AI, Google Gemini, Bing Copilot',
    'methodology_standards': '<b>Standards referenced:</b> Google Search Quality Rater Guidelines (Dec 2025), Schema.org specification, Core Web Vitals (2026 thresholds), llms.txt emerging standard, RSL 1.0 licensing framework',

    # Crawler table data
    'status_allowed': 'Allowed',
    'status_blocked': 'Blocked',
    'status_unknown': 'Unknown',
    'rec_keep_allowed': 'Keep allowed',
    'rec_unblock': 'Unblock for visibility',

    # Disclaimer
    'disclaimer': 'This report was generated by the GEO-SEO Claude Code Analysis Tool. Scores and recommendations are based on automated analysis and industry benchmarks. Results should be validated with platform-specific testing.',

    # Glossary entries (list of [term, definition] pairs)
    'glossary_entries': [
        ['GEO', 'Generative Engine Optimization \u2014 optimizing content for AI search citation'],
        ['AIO', 'AI Overviews \u2014 Google\'s AI-generated answer boxes in search results'],
        ['E-E-A-T', 'Experience, Expertise, Authoritativeness, Trustworthiness'],
        ['SSR', 'Server-Side Rendering \u2014 generating HTML on the server for crawler access'],
        ['CWV', 'Core Web Vitals \u2014 Google\'s page experience metrics (LCP, INP, CLS)'],
        ['INP', 'Interaction to Next Paint \u2014 responsiveness metric (replaced FID March 2024)'],
        ['JSON-LD', 'JavaScript Object Notation for Linked Data \u2014 preferred structured data format'],
        ['sameAs', 'Schema.org property linking an entity to its profiles on other platforms'],
        ['llms.txt', 'Proposed standard file for guiding AI systems about site content'],
        ['IndexNow', 'Protocol for instantly notifying search engines of content changes'],
    ],

    # Default action plan items
    'default_quick_wins': [
        'Allow all Tier 1 AI crawlers in robots.txt (GPTBot, ClaudeBot, PerplexityBot)',
        'Add publication and last-updated dates to all content pages',
        'Add author bylines with credentials to blog posts and articles',
        'Create an llms.txt file to guide AI systems to your key content',
        'Add sameAs properties to Organization schema linking to all platform profiles',
    ],
    'default_medium_term': [
        'Restructure top 10 pages with question-based headings and direct answer blocks',
        'Implement comprehensive Organization + Article + Person schema markup',
        'Optimize content blocks for AI citability (134-167 word self-contained passages)',
        'Ensure server-side rendering for all public content pages',
        'Implement IndexNow protocol for Bing/Copilot indexing speed',
    ],
    'default_strategic': [
        'Build Wikipedia/Wikidata entity presence through press coverage and notability',
        'Develop active Reddit community engagement strategy in relevant subreddits',
        'Create YouTube content strategy aligned with AI-searched queries',
        'Establish original research/data publication program for unique citability',
        'Build topical authority through comprehensive content clusters',
    ],
}
